spring:
  application:
    name: eureka-server
server:
  port: 3000
eureka:
  server:
    enable-self-preservation: false 
    eviction-interval-timer-in-ms: 4000 
  instance:
    hostname: eureka3000.com
  client:
    serviceUrl:
      #defaultZone: http://eureka3000.com:3000/eureka,http://eureka3001.com:3001/eureka
      defaultZone: http://eureka3000.com:3000/eureka
