spring:
  profiles:
    active: pro

---

server:
  port: 8203


spring:
  profiles: dev
  application:
    name: cloud-dev111


---

server:
  port: 8033

spring:
  profiles: pro
  application:
    name: cloud-pro22222
